name: book_store
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Commonly used icons for iOS-style applications
  cupertino_icons: ^1.0.8

  # State management package
  provider: ^6.1.2

  # Internationalization utilities
  intl: ^0.19.0

  # This package is required to enable Flutter's localization support
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^4.0.0

  # Package to help with internationalization
  intl_utils: ^2.8.7  # Ensure this package is added here

flutter:
  uses-material-design: true

  # Add the localizations assets for the intl package
  # Ensure the folder structure matches your localization files
  assets:
    - lib/l10n/

  # Specify the localization support
  generate: true  # Enable code generation for localization files
